image:
  file: .gitpod.dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 8025
    onOpen: ignore
  - port: 1025
    onOpen: ignore

tasks:
  - command: wget -q https://github.com/PrestaShop/PrestaShop/releases/download/1.7.7.1/prestashop_1.7.7.1.zip
  - command: unzip prestashop_1.7.7.1.zip -d ./public_html
  # WIP todo : lunch autoconfig
  # WIP todo : remove zip after install
  - command: apache2ctl start # start Apache server
  
  # start MailHog (SMTP testing tool) 
  - command: mailhog -api-bind-addr 127.0.0.1:8025 -ui-bind-addr 127.0.0.1:8025 -smtp-bind-addr 127.0.0.1:1025
